version: "3.5"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vvcb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepass
    volumes:
      - ./data/mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: vvcb-backend/server:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://vvcbuser:examplepass@mongo:27017/vvcb
    stdin_open: true  # -i
    tty: true         # -t